services:
    louvre_resa.validator.NombreBilletVendu:
        class: Louvre\ResaBundle\Validator\NombreBilletVenduValidator
        arguments: ["@doctrine.orm.entity_manager"] 
        tags:
            - { name: validator.constraint_validator, alias: Louvre_resa_nombreBilletVendu }
    louvre_resa.CalculPrix:
        class: Louvre\ResaBundle\Services\CalculPrix
    louvre_resa.Message:
        class: Louvre\ResaBundle\Services\Message
        arguments: ["@mailer", "@templating"] 
    louvre_resa.Stripe:
        class: Louvre\ResaBundle\Services\Stripe
        arguments: ["@router"] 

parameters:
    # api_stripe: "%env(DB_PASSWORD)%"

